modules:
  - name: Fix podman
    type: shell
    body:
      command: |
        control newuidmap public
        control newgidmap public

  - name: Enable sudo
    type: shell
    body:
      command: |
        control sudowheel enabled

  - name: Set locale
    type: copy
    body:
      source: files/locale.conf
      destination: /etc/locale.conf
      replace: true

  - type: copy
    body:
      source: files/locale.conf
      destination: /etc/sysconfig/i18n
      replace: true
