name: Build nightly images

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  LOCAL_BUILD_NAME: localhost/core
  REGISTRY: altlinux.space

jobs:
  gather-build-data:
    name: Gather build data
    runs-on: als-tiny

    outputs:
      date: ${{ steps.date.outputs.date }}
      year: ${{ steps.date.outputs.year }}
      month: ${{ steps.date.outputs.month }}
      day: ${{ steps.date.outputs.day }}
      pretty-date: ${{ steps.date.outputs.pretty-date }}
      commit: ${{ steps.get_commit.outputs.commit }} 
      tag: ${{ steps.latest_tag.outputs.tag }}
      release: ${{ steps.latest_tag.outputs.release }} 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get latest tag
      id: latest_tag
      uses: alt-atomic/actions/get-tag@main
      with:
        desired-tag: ${{ github.ref_name }}

    - name: Get date
      id: date
      uses: alt-atomic/actions/parse-date@main
      with:
        date: ${{ steps.latest_tag.outputs.date }}

  build-minimal:
    name: Build ${{ matrix.arch }} minimal image
    needs:
    - gather-build-data
    runs-on: ${{ matrix.runner }}
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            larch: x86_64
            runner: als-huge
          - arch: arm64
            larch: aarch64
            runner: self-hosted-arm64-huge
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        tag: ${{ needs.gather-build-data.outputs.tag }}

    - name: Build image
      uses: ./.forgejo/actions/build-and-push-release-image
      with:
        build: minimal
        image-name: ${{ github.repository }}-minimal
        name-pretty: '(Minimal)'
        year: ${{ needs.gather-build-data.outputs.year }}
        month: ${{ needs.gather-build-data.outputs.month }}
        day: ${{ needs.gather-build-data.outputs.day }}
        version: ${{ github.ref_name }}
        pretty-date: ${{ needs.gather-build-data.outputs.pretty-date }}
        registry-token: ${{ secrets.REGISTRY_TOKEN }}
        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}
        local-build-name: localhost/core/minimal
        arch: ${{ matrix.arch }}
        larch: ${{ matrix.larch }}

  build-default:
    name: Build ${{ matrix.arch }} default image
    needs:
    - gather-build-data
    - build-minimal
    runs-on: ${{ matrix.runner }}
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            larch: x86_64
            runner: als-huge
          - arch: arm64
            larch: aarch64
            runner: self-hosted-arm64-huge
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        tag: ${{ needs.gather-build-data.outputs.tag }}

    - name: Build image
      uses: ./.forgejo/actions/build-and-push-release-image
      with:
        build: default
        image-name: ${{ github.repository }}
        name-pretty: ''
        year: ${{ needs.gather-build-data.outputs.year }}
        month: ${{ needs.gather-build-data.outputs.month }}
        day: ${{ needs.gather-build-data.outputs.day }}
        version: ${{ github.ref_name }}
        pretty-date: ${{ needs.gather-build-data.outputs.pretty-date }}
        registry-token: ${{ secrets.REGISTRY_TOKEN }}
        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}
        local-build-name: localhost/core
        arch: ${{ matrix.arch }}
        larch: ${{ matrix.larch }}

  manifest-minimal:
    name: Multiarch minimal manifest push
    needs:
    - gather-build-data
    - build-minimal
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus

    steps:
      - name: Create manifest
        uses: alt-atomic/actions/create-manifest@9553cbf63780d0252b503904b7e3ca35f566a943
        with:
          registry: ${{ env.REGISTRY }}
          registry-username: "<token>"
          registry-password: ${{ secrets.REGISTRY_TOKEN }}
          image-name: ${{ github.repository }}-minimal/stable
          arch-tags: amd64 arm64
          image-tag: latest
          image-aliases: ${{ needs.gather-build-data.outputs.date }} ${{ needs.gather-build-data.outputs.tag }} ${{ needs.gather-build-data.outputs.release }} ${{ needs.gather-build-data.outputs.commit }}
          cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
          cosign-password: ${{ secrets.COSIGN_PASSWORD }}

  manifest-default:
    name: Multiarch default manifest push
    needs:
    - gather-build-data
    - build-default
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus

    steps:
      - name: Create manifest
        uses: alt-atomic/actions/create-manifest@9553cbf63780d0252b503904b7e3ca35f566a943
        with:
          registry: ${{ env.REGISTRY }}
          registry-username: "<token>"
          registry-password: ${{ secrets.REGISTRY_TOKEN }}
          image-name: ${{ github.repository }}/stable
          arch-tags: amd64 arm64
          image-tag: latest
          image-aliases: ${{ needs.gather-build-data.outputs.date }} ${{ needs.gather-build-data.outputs.tag }} ${{ needs.gather-build-data.outputs.release }} ${{ needs.gather-build-data.outputs.commit }}
          cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
          cosign-password: ${{ secrets.COSIGN_PASSWORD }}

  release:
    name: Publish release
    runs-on: als-tiny
    needs:
    - manifest-minimal
    - manifest-default
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get changes between tags
        id: changes
        uses: https://github.com/simbo/changes-between-tags-action@v1
        with:
          tag-pattern: '^[0-9]+\.[0-9]+\.[0-9]+$'
          include-hashes: false

      - name: Publish release
        id: create_release
        uses: https://github.com/softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.changes.outputs.tag }}
          name: "Release ${{ steps.changes.outputs.tag }}"
          body: "${{ steps.changes.outputs.changes }}"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
