name: Build nightly images

on:
  workflow_dispatch:
  schedule:
  # Every day at 4 a.m.
  - cron: '0 4 * * *'
  push:
    branches:
    - 'nightly-*'
    - 'main'
  pull_request:

env:
  LOCAL_BUILD_NAME: localhost/core
  REGISTRY: altlinux.space

jobs:
  gather-build-data:
    name: Gather build data
    runs-on: als-tiny

    outputs:
      date: ${{ steps.date.outputs.date }}
      year: ${{ steps.date.outputs.year }}
      month: ${{ steps.date.outputs.month }}
      day: ${{ steps.date.outputs.day }}
      pretty-date: ${{ steps.date.outputs.pretty-date }}
      commit: ${{ steps.get_commit.outputs.commit }} 

    steps:
    - name: Get date
      id: date
      uses: alt-atomic/actions/parse-date@main

    - name: Checkout repository
      uses: actions/checkout@v4

    - id: get_commit
      name: Get current commit
      run: |
        echo "commit=$(git rev-parse HEAD)" >> $FORGEJO_OUTPUT

  build-minimal:
    name: Build minimal ${{ matrix.arch }} image
    needs:
    - gather-build-data
    runs-on: ${{ matrix.runner }}
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus
    strategy:
      matrix:
        arch:
        - amd64
        - arm64
        include:
        - arch: amd64
          larch: x86_64
          runner: als-huge
        - arch: arm64
          larch: aarch64
          runner: self-hosted-arm64-huge

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build minimal image
      uses: alt-atomic/actions/build-and-push@4c82db863a5f8c3b0abbcefd1a1be8c7e846fc00
      with:
        image-name: >-
          ${{
            github.ref_name == 'main' && 
            format('{0}-minimal/nightly', github.repository) || 
            format('{0}-minimal/nightly-branch', github.repository) 
          }}
        image-tag: ${{ matrix.arch }}
        arch: ${{ matrix.arch }}
        containerfile-path: ./container-files/main-minimal

        registry-password: ${{ secrets.REGISTRY_TOKEN }}

        pretty-name: ALT Atomic Core Nightly
        version: ${{ needs.gather-build-data.outputs.year }}${{ needs.gather-build-data.outputs.month }}${{ needs.gather-build-data.outputs.day }}

        vendor: ALT Atomic Team
        description: Nightly Core image for ALT Atomic distros
        licenses: GPL-3.0-or-later
        url: atomic.alt-gnome.ru
        authors: ALT Atomic Team

        repo-date: ${{ needs.gather-build-data.outputs.pretty-date }}

        build-args: |
          YEAR=${{ needs.gather-build-data.outputs.year }}
          MONTH=${{ needs.gather-build-data.outputs.year }}
          DAY=${{ needs.gather-build-data.outputs.year }}
          IMAGE_TYPE=nightly
          IMAGE=registry.altlinux.org/sisyphus/base:latest
          ARCH=${{ matrix.larch }}
          VERSION=${{ needs.gather-build-data.outputs.year }}${{ needs.gather-build-data.outputs.month }}${{ needs.gather-build-data.outputs.day }}

        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}
        
        local-build-name: localhost/core-minimal

  build-default:
    name: Build default ${{ matrix.arch }} image
    needs:
    - build-minimal
    - gather-build-data
    runs-on: ${{ matrix.runner }}
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus
    strategy:
      matrix:
        arch:
        - amd64
        - arm64
        include:
        - arch: amd64
          larch: x86_64
          runner: als-huge
        - arch: arm64
          larch: aarch64
          runner: self-hosted-arm64-huge

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build minimal image
      uses: alt-atomic/actions/build-and-push@4c82db863a5f8c3b0abbcefd1a1be8c7e846fc00
      with:
        image-name: >-
          ${{
            github.ref_name == 'main' && 
            format('{0}/nightly', github.repository) || 
            format('{0}/nightly-branch', github.repository) 
          }}
        image-tag: ${{ matrix.arch }}
        arch: ${{ matrix.arch }}
        containerfile-path: ./container-files/main-default

        registry-password: ${{ secrets.REGISTRY_TOKEN }}

        pretty-name: ALT Atomic Core Nightly
        version: ${{ needs.gather-build-data.outputs.year }}${{ needs.gather-build-data.outputs.month }}${{ needs.gather-build-data.outputs.day }}

        vendor: ALT Atomic Team
        description: Nightly Core image for ALT Atomic distros
        licenses: GPL-3.0-or-later
        url: atomic.alt-gnome.ru
        authors: ALT Atomic Team

        repo-date: ${{ needs.gather-build-data.outputs.pretty-date }}

        build-args: |
          YEAR=${{ needs.gather-build-data.outputs.year }}
          MONTH=${{ needs.gather-build-data.outputs.year }}
          DAY=${{ needs.gather-build-data.outputs.year }}
          IMAGE_TYPE=nightly
          IMAGE=${{ env.REGISTRY }}/${{ github.repository }}-minimal/${{ github.ref_name == 'main' && 'nightly' || 'nightly-branch' }}:${{ matrix.arch }}
          ARCH=${{ matrix.larch }}
          VERSION=${{ needs.gather-build-data.outputs.year }}${{ needs.gather-build-data.outputs.month }}${{ needs.gather-build-data.outputs.day }}

        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}
        
        local-build-name: localhost/core

  manifest-minimal:
    name: Multiarch minimal manifest push
    needs:
    - build-minimal
    - gather-build-data
    if: github.event_name != 'pull_request'
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus

    steps:
    - name: Create manifest
      uses: alt-atomic/actions/create-manifest@9553cbf63780d0252b503904b7e3ca35f566a943
      with:
        registry: ${{ env.REGISTRY }}
        registry-username: "<token>"
        registry-password: ${{ secrets.REGISTRY_TOKEN }}
        image-name: >-
          ${{ 
            github.ref_name == 'main' && 
            '${{ github.repository }}-minimal/nightly' || 
            '${{ github.repository }}-minimal/nightly-branch' 
          }}
        arch-tags: amd64 arm64
        image-tag: >-
          ${{
            github.ref_name == 'main' &&
            'latest' ||
            github.ref_name
          }}
        image-aliases: >-
          ${{ 
            github.ref_name == 'main' && 
            needs.gather-build-data.outputs.date || 
            '' 
          }} ${{ needs.gather-build-data.outputs.commit }}
        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}

  manifest-default:
    name: Multiarch default manifest push
    needs:
    - build-default
    - gather-build-data
    if: github.event_name != 'pull_request'
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus

    steps:
    - name: Create manifest
      uses: alt-atomic/actions/create-manifest@9553cbf63780d0252b503904b7e3ca35f566a943
      with:
        registry: ${{ env.REGISTRY }}
        registry-username: "<token>"
        registry-password: ${{ secrets.REGISTRY_TOKEN }}
        image-name: >-
          ${{ 
            github.ref_name == 'main' && 
            '${{ github.repository }}/nightly' || 
            '${{ github.repository }}/nightly-branch' 
          }}
        arch-tags: amd64 arm64
        image-tag: >-
          ${{
            github.ref_name == 'main' &&
            'latest' ||
            github.ref_name
          }}
        image-aliases: >-
          ${{ 
            github.ref_name == 'main' && 
            needs.gather-build-data.outputs.date || 
            '' 
          }} ${{ needs.gather-build-data.outputs.commit }}
        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}


  run-derivatives:
    name: Run ${{ matrix.image }} build-nightly workflow
    needs:
    - manifest-minimal
    - manifest-default
    if: >
      github.event_name == 'schedule'
    runs-on: als-tiny
    strategy:
      matrix:
        image:
        - kyanite
        - onyx

    steps:
    - name: Trigger rebuild
      uses: actions/forgejo-script@v1
      env:
        IMAGE: ${{ matrix.image }}
      with:
        github-token: ${{ secrets.REBUILD }}
        script: |
          await forgejo.repos.dispatchWorkflow(
            "alt-atomic",
            process.env.IMAGE,
            "build-nightly.yml", 
            {
              ref: "main",
            },
          );
