name: Build everyday stable images

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
  schedule:
  # Every day at 4 a.m.
  - cron: '0 4 * * *'

env:
  REGISTRY: altlinux.space

  PRETTY_NAME: ALT Atomic Core
  VENDOR: ALT Atomic Team
  DESCRIPTION: Core image for ALT Atomic distros
  LICENSES: GPL-3.0-or-later
  URL: atomic.alt-gnome.ru
  AUTHORS: ALT Atomic Team

jobs:
  gather-build-data:
    name: Gather build data
    runs-on: als-tiny

    outputs:
      date: ${{ steps.date.outputs.date }}
      year: ${{ steps.date.outputs.year }}
      month: ${{ steps.date.outputs.month }}
      day: ${{ steps.date.outputs.day }}
      pretty-date: ${{ steps.date.outputs.pretty-date }}
      version: ${{ format('{0}-{1}', steps.get_tag.outputs.tag, steps.date.outputs.date) }}
      aliases: ${{ format('{0} {1}', steps.date.outputs.date, steps.get_tag.outputs.tag) }}

    steps:
    - name: Get date
      id: date
      uses: alt-atomic/actions/parse-date@main

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - id: get_tag
      name: Get latest tag
      uses: alt-atomic/actions/get-tag@main

  build:
    name: Build ${{ matrix.arch }} images
    needs:
    - gather-build-data
    runs-on: ${{ matrix.runner }}
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus
    strategy:
      matrix:
        arch:
        - amd64
        - arm64
        include:
        - arch: amd64
          larch: x86_64
          runner: als-huge
        - arch: arm64
          larch: aarch64
          runner: self-hosted-arm64-huge

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build minimal image
      uses: alt-atomic/actions/build-and-push@c882944ee9b49d04f3f2030aa47c435515a66657
      with:
        image-name: ${{ format('{0}-minimal/stable/{1}', github.repository, matrix.arch) }}
        image-tag: latest
        image-aliases: ${{ needs.gather-build-data.outputs.aliases }}
        arch: ${{ matrix.arch }}
        containerfile-path: ./container-files/main-minimal
        local-build-name: localhost/core-minimal

        registry-password: ${{ secrets.REGISTRY_TOKEN }}

        pretty-name: ${{ env.PRETTY_NAME }}
        version: ${{ needs.gather-build-data.outputs.version }}
        vendor: ${{ env.VENDOR }}
        description: ${{ env.DESCRIPTION }}
        licenses: ${{ env.LICENSES }}
        url: ${{ env.URL }}
        authors: ${{ env.AUTHORS }}
        repo-date: ${{ needs.gather-build-data.outputs.pretty-date }}

        build-args: |
          YEAR=${{ needs.gather-build-data.outputs.year }}
          MONTH=${{ needs.gather-build-data.outputs.month }}
          DAY=${{ needs.gather-build-data.outputs.day }}
          IMAGE_TYPE=stable
          IMAGE=registry.altlinux.org/sisyphus/base:latest
          ARCH=${{ matrix.larch }}
          VERSION=${{ needs.gather-build-data.outputs.version }}

        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}

    - name: Build default image
      uses: alt-atomic/actions/build-and-push@c882944ee9b49d04f3f2030aa47c435515a66657
      with:
        image-name: ${{ format('{0}/stable/{1}', github.repository, matrix.arch) }}
        image-tag: latest
        image-aliases: ${{ needs.gather-build-data.outputs.aliases }}
        arch: ${{ matrix.arch }}
        containerfile-path: ./container-files/main-default
        local-build-name: localhost/core

        registry-password: ${{ secrets.REGISTRY_TOKEN }}

        pretty-name: ${{ env.PRETTY_NAME }}
        version: ${{ needs.gather-build-data.outputs.version }}
        vendor: ${{ env.VENDOR }}
        description: ${{ env.DESCRIPTION }}
        licenses: ${{ env.LICENSES }}
        url: ${{ env.URL }}
        authors: ${{ env.AUTHORS }}
        repo-date: ${{ needs.gather-build-data.outputs.pretty-date }}

        build-args: |
          YEAR=${{ needs.gather-build-data.outputs.year }}
          MONTH=${{ needs.gather-build-data.outputs.month }}
          DAY=${{ needs.gather-build-data.outputs.day }}
          IMAGE_TYPE=stable
          IMAGE=localhost/core-minimal
          ARCH=${{ matrix.larch }}
          VERSION=${{ needs.gather-build-data.outputs.version }}

        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}

  manifest:
    name: Multiarch ${{ matrix.name }} manifest push
    needs:
    - build
    - gather-build-data
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus
    strategy:
      matrix:
        include:
        - name: minimal
          suffix: -minimal
        - name: default
          suffix: ''

    steps:
    - name: Create manifest
      uses: alt-atomic/actions/create-manifest@0a7fd4632a415b0f4316c37d9be29325dbe32af9
      with:
        registry: ${{ env.REGISTRY }}
        registry-username: "<token>"
        registry-password: ${{ secrets.REGISTRY_TOKEN }}
        image-name: ${{ format('{0}{1}/stable', github.repository, matrix.suffix) }}
        arch-tags: amd64 arm64
        image-wildcard: ${{ format('{0}/{1}{2}/stable/@ARCH@:latest', env.REGISTRY, github.repository, matrix.suffix) }}
        image-tag: latest
        image-aliases: ${{ needs.gather-build-data.outputs.aliases }}
        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}
