name: Build nightly images

on:
  workflow_dispatch:
  schedule:
  # Every day at 4 a.m.
  - cron: '0 4 * * *'
  push:
    branches:
    - 'nightly-*'
    - 'main'
  pull_request:

env:
  LOCAL_BUILD_NAME: localhost/core
  REGISTRY: altlinux.space

jobs:
  gather-build-data:
    name: Gather build data
    runs-on: als-tiny

    outputs:
      date: ${{ steps.date.outputs.date }}
      year: ${{ steps.date.outputs.year }}
      month: ${{ steps.date.outputs.month }}
      day: ${{ steps.date.outputs.day }}
      pretty-date: ${{ steps.date.outputs.pretty-date }}
      commit: ${{ steps.get_commit.outputs.commit }} 

    steps:
    - name: Get date
      id: date
      uses: alt-atomic/actions/parse-date@main

    - name: Checkout repository
      uses: actions/checkout@v4

    - id: get_commit
      name: Get current commit
      run: |
        echo "commit=$(git rev-parse HEAD)" >> $FORGEJO_OUTPUT

  build-minimal:
    name: Build minimal ${{ matrix.arch }} image
    needs:
    - gather-build-data
    runs-on: ${{ matrix.runner }}
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus
    strategy:
      matrix:
        arch:
        - amd64
        - arm64
        include:
        - arch: amd64
          larch: x86_64
          runner: als-huge
        - arch: arm64
          larch: aarch64
          runner: self-hosted-arm64-huge

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build minimal image
      uses: ./.forgejo/actions/build-and-push-nightly-image
      with:
        build: minimal
        image-name: ${{ github.repository }}-minimal
        name-pretty: '(Minimal)'
        year: ${{ needs.gather-build-data.outputs.year }}
        month: ${{ needs.gather-build-data.outputs.month }}
        day: ${{ needs.gather-build-data.outputs.day }}
        pretty-date: ${{ needs.gather-build-data.outputs.pretty-date }}
        commit: ${{ needs.gather-build-data.outputs.commit }}
        registry-token: ${{ secrets.REGISTRY_TOKEN }}
        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}
        local-build-name: localhost/core/minimal
        need-rechunk: 'false'
        arch: ${{ matrix.arch }}
        larch: ${{ matrix.larch }}

  build-default:
    name: Build minimal ${{ matrix.arch }} image
    needs:
    - build-minimal
    - gather-build-data
    runs-on: ${{ matrix.runner }}
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus
    strategy:
      matrix:
        arch:
        - amd64
        - arm64
        include:
        - arch: amd64
          larch: x86_64
          runner: als-huge
        - arch: arm64
          larch: aarch64
          runner: self-hosted-arm64-huge

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build minimal image
      uses: ./.forgejo/actions/build-and-push-nightly-image
      with:
        build: default
        image-name: ${{ github.repository }}
        name-pretty: ''
        year: ${{ needs.gather-build-data.outputs.year }}
        month: ${{ needs.gather-build-data.outputs.month }}
        day: ${{ needs.gather-build-data.outputs.day }}
        pretty-date: ${{ needs.gather-build-data.outputs.pretty-date }}
        commit: ${{ needs.gather-build-data.outputs.commit }}
        registry-token: ${{ secrets.REGISTRY_TOKEN }}
        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}
        local-build-name: localhost/core
        need-rechunk: 'false'
        arch: ${{ matrix.arch }}
        larch: ${{ matrix.larch }}

  manifest-minimal:
    name: Multiarch minimal manifest push
    needs:
    - build-minimal
    - gather-build-data
    if: >
      contains(fromJSON('["push", "workflow_dispatch", "schedule"]'), github.event_name)
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus

    steps:
    - name: Create manifest
      uses: alt-atomic/actions/create-manifest@9553cbf63780d0252b503904b7e3ca35f566a943
      with:
        registry: ${{ env.REGISTRY }}
        registry-username: "<token>"
        registry-password: ${{ secrets.REGISTRY_TOKEN }}
        image-name: >-
          ${{ 
            github.ref_name == 'main' && 
            '${{ github.repository }}-minimal/nightly' || 
            '${{ github.repository }}-minimal/nightly-branch' 
          }}
        arch-tags: amd64 arm64
        image-tag: >-
          ${{
            github.ref_name == 'main' &&
            'latest' ||
            github.ref_name
          }}
        image-aliases: >-
          ${{ 
            github.ref_name == 'main' && 
            needs.gather-build-data.outputs.date || 
            '' 
          }} ${{ needs.gather-build-data.outputs.commit }}
        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}

  manifest-default:
    name: Multiarch minimal manifest push
    needs:
    - build-default
    - gather-build-data
    if: >
      contains(fromJSON('["push", "workflow_dispatch", "schedule"]'), github.event_name)
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus

    steps:
    - name: Create manifest
      uses: alt-atomic/actions/create-manifest@9553cbf63780d0252b503904b7e3ca35f566a943
      with:
        registry: ${{ env.REGISTRY }}
        registry-username: "<token>"
        registry-password: ${{ secrets.REGISTRY_TOKEN }}
        image-name: >-
          ${{ 
            github.ref_name == 'main' && 
            '${{ github.repository }}/nightly' || 
            '${{ github.repository }}/nightly-branch' 
          }}
        arch-tags: amd64 arm64
        image-tag: >-
          ${{
            github.ref_name == 'main' &&
            'latest' ||
            github.ref_name
          }}
        image-aliases: >-
          ${{ 
            github.ref_name == 'main' && 
            needs.gather-build-data.outputs.date || 
            '' 
          }} ${{ needs.gather-build-data.outputs.commit }}
        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}


  run-derivatives:
    name: Run ${{ matrix.image }} build-nightly workflow
    needs:
    - manifest-minimal
    - manifest-default
    if: >
      github.event_name == 'schedule'
    runs-on: als-tiny
    strategy:
      matrix:
        image:
        - kyanite
        - onyx

    steps:
    - name: Trigger rebuild
      uses: actions/forgejo-script@v1
      env:
        IMAGE: ${{ matrix.image }}
      with:
        github-token: ${{ secrets.REBUILD }}
        script: |
          await forgejo.repos.dispatchWorkflow(
            "alt-atomic",
            process.env.IMAGE,
            "build-nightly.yml", 
            {
              ref: "main",
            },
          );
