modules:
  - name: Fix podman
    type: shell
    body:
      command: |
        control newuidmap public
        control newgidmap public

  - name: Enable sudo
    type: shell
    body:
      command: |
        control sudowheel enabled

  - name: Disable getty
    type: systemd
    body:
      targets:
        - getty@.service
      enabled: false

  - name: Enable kmsconvt
    type: systemd
    body:
      targets:
        - kmsconvt@.service
      enabled: true