modules:
  - name: Fix podman
    type: shell
    body:
      command: |
        control newuidmap public
        control newgidmap public

  - name: Enable sudo
    type: shell
    body:
      command: |
        control sudowheel enabled
