name: Build Base image

on:
  schedule:
    - cron: '0 0 1 * *' # раз в месяц
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push alt-image-base
        uses: docker/build-push-action@v4
        with:
          context: alt-image-base
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/alt-image-base:latest
          platforms: linux/amd64

      - name: Build and push alt-image
        uses: docker/build-push-action@v4
        with:
          context: alt-image
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/alt-image:latest
          platforms: linux/amd64          
